### ISSUE TITLE
Debate sobre tecnologias levantadas, Product Backlog pensado e Documento de Visão desenvolvido

### ISSUE THREAD

**Issue by Bruno-Felix** [fga-eps-mds/2020.1-Vamos_Cuidar#43]
### Descrição:
Issue destinada a reunião de debate de todas as tecnologias levantadas para uma aplicação web.

### Tarefas:
- [x] Comentar sobre as tecnologias levantadas - Back-end; Bruno e Enzo (#42);
- [x] Comentar sobre as tecnologias levantadas - Banco de dados: Daniel P. e Bruno (#44);
- [x] Comentar sobre as tecnologias levantadas - Front-end: Denys e Danie P. (#39);
- [x] Comentar sobre as tecnologias levantadas - Docker: Emily e Daniel B. (#40);
- [x] Comentar sobre o Product Backlog pensado (#46);
- [x] Comentar sobre o Documento de Visão (#41).
- **Reunião será realizada quarta(19/09) as 20h.**

### Critérios de aceitação:
- [x] Debater as tecnologias levantadas na reunião;
- [x] Destacar aquelas que potencialmente serão usadas no desenvolvimento do produto;
- [x] Debater Product Backlog e possíveis melhoras;
- [x] Debater Documento de Visão e possíveis melhoras;
- [x] Comentar nessa issue tudo que foi debatido e concordado na reunião.

**Comment by Bruno-Felix** [comment]
Foi definido de tirar o tópico de outros requisitos do Documento de Visão

**Comment by Bruno-Felix** [comment]
Falta @DenysRogeres enviar seus incrementos para o Documento de Visão
