### ISSUE TITLE
Estudo e inserção do template de Roadmap

### ISSUE THREAD

**Issue by enzoggqs** [fga-eps-mds/2020.1-Vamos_Cuidar#45]
### Descrição:
Issue feita para estudar o conceito de Roadmap e para a inserção do template de Roadmap

### Tarefas:

- [x] Estudo do conceito de Roadmap;
- [x] Inserção do template de Roadmap.

### Critérios de aceitação:

- [x] Conclusão dos estudos de Roadmap;
- [x] Conclusão e inserção do documento de Roadmap.

**Comment by enzoggqs** [comment]
Numa pesquisa rápida no YouTube, achei esse [Vídeo](https://www.youtube.com/watch?v=pJvLADCduzw&ab_channel=Gest%C3%A3o%26Carreira) explicando o que é o Roadmap.

**Comment by enzoggqs** [comment]
Também achei esse [site](https://gobacklog.com/blog/roadmap/) que dá uma base de como fazer seu Roadmap.

**Comment by Bruno-Felix** [comment]
Seguindo a orientação da issue #3, O grupo Acacia fez o seu Roadmap como um Projects no próprio GitHub:

https://github.com/fga-eps-mds/2019.2-Acacia/projects/3
