### ISSUE TITLE
Padrão de contribuição e trabalho no projeto

### ISSUE THREAD

**Issue by emysdias** [fga-eps-mds/2020.1-Vamos_Cuidar#5]
Descrição:
Definir os padrões de commit, de criação de issues, e como será a gestão das sprints

Tarefas:
- [x] Gestão de Sprint (documentação sprint + rituais + boas praticas); (issue #14)
- [x] Padrão de commit;
- [x] Padrão de issues;
- [x] Processo de contribuição;
- [x] Padrão de branch #20;
- [x] Obter referencias, exemplos e dicas de um bom README.

Critérios de Aceitação:
- [x] Todos os integrantes concordarem com os padrões elaborados;
- [x] Demonstrar como será a gestão das sprints.  (issue #14)
---
### Padrão de Commit
- Sempre verificar se sua alteração está sendo feita na branch correta, seguindo o design de fluxo do Gitflow;
- Em **português**;
- No gerúndio;
- Sempre com o **número da issue** que esse commit está relacionado;
- Melhor 10 commits sobre coisas específicas do que 1 genérica com muitas coisas;
- Tentar usar o máximo possível de infos no nome do commit(Dica: usar nomes de **variável, arquivo ou tela no commit**);
- Ex.: #999 Criando botão informacoesUsuario na página - visualizarPostagem 
_(Aqui fica bem claro que existe uma página chamada visualizarPostagem.html e nela foi implementada um botão chamado informacoesUsuario)_

### Padrão de Issues #4 
- A issue deve **especifica** o suficiente para abordar sua descrição
- Se ler e perceber que alguma tarefa ou critério não casa com a descrição da issue, talvez seja a hora de pensar em criar uma nova issue para abordar essa tal tarefa ou critério.
- Issue, como já dito pela professora, **é prova do seu trabalho e participação**

**Descrição**
Clara e objetiva descrição da issue.

**Tarefas**
- Ponto a ser considerado no issue;
- [x] Ação a ser feita na issue; 

**Critério de Avaliação**
-  Ponto a avaliado na issue;
- [x] Ação a ser verificada na issue;

Em caso de **Estudo** de Documento:
- [x] Integrantes responsáveis precisam concordar que as referencias compartilhadas são suficiente para a produção do documento.

Em caso de **Produção** de Documento:
- [x] Todos os integrantes precisam concordar com o Documento Criado.

### Processo de Contribuição #4 
1. Fazer **fork** do projeto #2 
2. **Clonar seu** repositório remoto;
3. Fazer as mudanças **necessárias** e as **funcionalidades** planejadas;
4. Verificar se o repositório não tem **mudanças** no repositório principal do projeto;
5. **Subir** tudo feito para seu repositório remoto;
6. Dá **pull request** direto pelo GitHub;
6.1 **Explicar na descrição** do pull request o que ele aborda e as mudanças/implementações foram feitas;
7. Seu pull request ser **aceito** repositório principal do projeto.

### Referencias de um bom README
- awesome-readme: [repositório](https://github.com/matiassingers/awesome-readme)
- README-ecoleta: [repositório](https://github.com/tgmarinho/README-ecoleta)

**Comment by emysdias** [comment]
![padrãp](https://user-images.githubusercontent.com/52640974/90790862-ea50c380-e2de-11ea-905e-511c8ad34745.png)

- Padrão das issues, com descrição, tarefas e critérios de aceitação

**Comment by emysdias** [comment]
Descrição:
Descrever sobre o que é a issue

Tarefas:
- [ ] o que terá que ser feito

Critérios de Aceitação:
- [ ] Qual vai ser a métrica para saber se a atividade foi feita


- Esse será o padrão das issues

**Comment by Bruno-Felix** [comment]
Uma sugestão seria ver padrões usado em outro semestres, relacionando com a issue #3

**Comment by Bruno-Felix** [comment]
#5 Inseri meus eventos no Google Agendas. @balves@gmail.com

Acredito que esse tópico: **"Todos inserem seus compromissos no Google Agendas."** acabou não condizendo com o proposito da issue.

Talvez criar uma outra issue sobre organização e estratégia?

**Comment by DenysRogeres** [comment]
> #5 Tenho uma dúvida @DenysRogeres posso usar como critério de aprovação criar uma issue para o Sprint seguinte? Ou tenho que esperar a Sprint atual se encerrar para criar uma nova issue?

@Bruno-Felix tudo isso é relatado no Sprint Retrospective e assim que essa etapa é finalizada, isso entra pra próxima Sprint Planning. Na próxima reunião eu irei explicar melhor sobre cada etapa.

**Comment by DenysRogeres** [comment]
#5 Separei a parte de gestão de sprint em uma nova issue, acredito que assim fica mais sucinto.

**Comment by Bruno-Felix** [comment]
#5 Pode acontecer dessa issue estar associada a criação Pull request e issue templates da issue #4.

**Comment by Bruno-Felix** [comment]
#5 Talvez isso tudo precise de alguma documentação, procurar, como recomendado na issue #3, de como isso será documentado

**Comment by emysdias** [comment]
#5 **Padrão de commit**  colocar no gerúndio, exemplo ( #5 Criando botão )

**Comment by Bruno-Felix** [comment]
> > #5 @emysdias:
> > ```
> > * Fiz processo de commit duvidoso:
> >   
> >   * Fiz um fork do repositório;
> >   * Fiz as mudanças e commitei;
> >   * Dei push pro meu fork do repositório com a #7 ;
> >   * Deu um pull request para o repositório principal pelo próprio GitHub;
> >   * Eu mesmo aceitei o pull request (o que está errado, mas é só pra testar);
> >   * Fez link com a #7 mas o merge gerou uma #8 como se fosse uma nova issue.
> >   * Na #9 novamente criou a #10 igual em cima, mas quando fiz mais um pull request e editei o nome do merge(excluindo a nova # que o merge criava) ele não gerou essa tal "nova issue" como a #8 e a #10.
> > 
> > * Criei dois arquivos na pasta /docs, um em inglês e outro em português, algum deles devem mudar. hehe
> > 
> > * ### **Como proceder, tem problema a #8 e a #10 existirem, na verdade é isso que linka o merge a issue original?**
> > 
> > * ### **Devemos criar arquivos em inglês ou português?**
> > ```
> 
> #5 Cheguei meio atrasada então acho q só sobrou a última pra responder, eu apoio deixar em inglês

#5 eu apoio tudo em português. Agora que sabemos o escopo do nosso projeto, que é concentrado na UnB, Em português deixaria o trabalho mais prático e ágil, principalmente na produção de documentos. Como gigantesca maioria que vai olhar esse projeto e os documentos são brasileiros estudantes da UnB, seria mais interessante ter a lingua portuguesa como padrão.

**Comment by DanielPortods** [comment]
#5 Também acho mais coerente deixar tudo em português.

**Comment by Bruno-Felix** [comment]
#5 Fiz um "apunhado" dos padrões e coloquei no comentário inicial da issue.

Também acrescentei Referencias de um bom README as tarefas.

Todos os integrantes precisam concordar com os padrões elaborados.

**Comment by DanielPortods** [comment]
#5 concordo com os padrões estabelecidos.

**Comment by emysdias** [comment]
#5 Concordo também, achei massa

**Comment by Bruno-Felix** [comment]
#5 O Padrão de branch foi conversado e será trabalhado na issue #4, no documento CONTRIBUTING.md.
